spring.application.name=userdirectory

mongodb.shards.ag.uri=mongodb://localhost:27017/shard_ag
mongodb.shards.hn.uri=mongodb://localhost:27018/shard_hn
mongodb.shards.oz.uri=mongodb://localhost:27019/shard_oz